export const SET_CATEGORIES = 'Set categories'
export const SET_FOLLOWED_TALENTS = 'Set followed talents'
export const SET_CURRENT_COMPETITION = 'Set current competition'
export const SET_COMPETITIONS = 'Set competitions'
export const INITIALIZE_STORE = 'Initialize store'
export const SET_BACK_TO_COMPETITION_SIGNUP = 'Back to competition signup'
